name: Generate Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap.xml
        run: |
          npx sitemap-generator https://toolswagon.site \
            --output ./sitemap.xml \
            --strip-querystring \
            --max-depth 0 \
            --verbose

      - name: Commit sitemap.xml
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml" || echo "No changes to commit"
          git push
