name: Generate Sitemap

on:
  push:
    branches: [main]  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap.xml at root
        run: |
          npx sitemap-generator https://toolswagon.site \
            --output ./sitemap.xml \
            --strip-querystring \
            --max-depth 0

      - name: Commit sitemap.xml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
