name: Generate Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap.xml
        run: |
          npx sitemap-generator https://toolswagon.site \
            --output ./sitemap.xml \
            --strip-querystring \
            --max-depth 0

      - name: Commit sitemap.xml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          if [[ `git status --porcelain` ]]; then
            git add sitemap.xml
            git commit -m "Auto update sitemap.xml"
            git push
          else
            echo "No changes to commit"
